.TH MKPASSWD 1 "2019-12-30" "Marco d'Itri" "Debian GNU/Linux"
.SH NAME
mkpasswd \- Overfeatured front end to crypt(3)
.SH SYNOPSIS
.B mkpasswd
.I PASSWORD
.RI [ SALT ]
.SH DESCRIPTION
.B mkpasswd
encrypts the given password with the
.BR crypt (3)
libc function, using the given salt.
.SH OPTIONS
.TP
.BR \-S " STRING\fR, \fP" \-\-salt= \fISTRING\fP
Use the
.I STRING
as salt.
If it begins with
.I $
then it will be passed straight to
.BR crypt (3)
without any checks.
.TP
.BR \-R " NUMBER\fR, \fP" \-\-rounds= \fINUMBER\fP
Use
.I NUMBER
rounds.
This argument is ignored if the method chosen
does not support variable rounds.
For the OpenBSD Blowfish method this is
the logarithm of the number of rounds.
The behavior is undefined if this option is used without
.IR \-\-method .
.TP
.BR \-m " TYPE\fR, \fP" \-\-method= \fITYPE\fP
Compute the password using the
.I TYPE
method.
If
.I TYPE
is
.I help
then the list of available methods is printed.
If
.I TYPE
begins and end with
.I $
characters then the string is passed to
.BR crypt_gensalt (3)
as-is.
.TP
.B \-5
Like
.IR \-\-method=md5crypt .
.TP
.BI \-P " NUM\fR, \fP" \-\-password-fd= NUM
Read the password from file descriptor
.I NUM
instead of using
.BR getpass (3).
If the file descriptor is not connected to a tty then no other text
than the hashed password is printed on stdout.
.TP
.BR \-s ", " \-\-stdin
Like
.IR \-\-password-fd=0 .
.SH ENVIRONMENT
.IP "MKPASSWD_OPTIONS"
A list of options which will be evaluated before the ones specified on the
command line.
.SH BUGS
If the
.I \-\-stdin
option is used then passwords containing some control
characters may not be read correctly.
.P
This program suffers of a bad case of featuritis.
.SH "SEE ALSO"
.BR passwd (1),
.BR passwd (5),
.BR crypt (3),
.BR crypt (5),
.BR crypt_gensalt (3),
.BR getpass (3).
.SH AUTHOR
.B mkpasswd
and this man page were written by Marco d'Itri
.RI < md@linux.it >
and are licensed under the terms of the GNU General Public License,
version 2 or later.
.\" SPDX-License-Identifier: GPL-2.0-or-later
