.TH WHOIS 1 "3 December 1999" "Marco d'Itri" "Debian GNU/Linux"
.SH NAME
whois \- client for the whois directory service
.SH SYNOPSIS
.B whois
[\~\fB-h\fP\~\fIHOST\fP\~]
[\~\fB-p\fP\~ \fIPORT\fP\~]
[\~\fB-aCFHlLMmrRSVx\fP\~]
[\~\fB-g\fP\~\fISOURCE:FIRST-LAST\fP\~]
[\~\fB-i\fP\~\fIATTR\fP\~]
[\~\fB-S\fP\~\fISOURCE\fP\~]
[\~\fB-T\fP\~\fITYPE\fP\~]
.I object

.B whois
[\~\fI-t\fP\~]
[\~\fI-v\fP\~]
.I template
.B whois
[\~\fI-q\fP\~]
.I keyword
.PP
.SH DESCRIPTION
\fBwhois\fP searches for an object in a \fIRFC-812\fP database.

This version of the whois client tries to guess the right server to
ask for the specified object. If no guess can be made it will connect
to whois.networksolutions.com for nic handles or whois.arin.net for
IPv4 addresses and network names.
.PP
.SH OPTIONS
.TP 8
.B \-h HOST
Connect to HOST.
.TP 8
.B \-H
Do not display the legal disclaimers some registries like to show you.
.TP 8
.B \-p PORT
Connect to PORT.
.TP 8
.B \--verbose
Be verbose.
.TP 8
.B \--help
Display online help.
.TP 8
Other options are flags understood by RIPE-like servers.
.SH NOTES
Please remember that \fIwhois.networksolutions.com\fP by default will
only search in the domains database. If you want to search for NIC handles
you have to prepend a \fI!\fP character. When you do this, the default
server becomes \fIwhois.networksolutions.com\fP.
.P
When querying \fIwhois.nic.mil\fP for AS numbers, the program will
automatically convert the request in the appropriate format, inserting
a space after the string "AS".
.P
When querying \fIwhois.corenic.net\fP, machine readable output is requested.
.P
RIPE-specific options are ignored when querying non-RIPE servers.
.SH Files
/etc/whois.conf
.SH ENVIRONMENT
.IP LANG
When querying \fIwhois.nic.ad.jp\fP english text is requested unless the
\fILANG\fP environment variable specifies a Japanese locale.
.IP "WHOIS_SERVER"
This server will be queried if the program cannot guess where some kind
of objects are located. If the variable does not exist then
\fIwhois.arin.net\fP will be queried.
.IP "WHOIS_HIDE"
If this variable is defined, legal disclaimers will be hidden even if
the \fI-H\fP flag is not used.
.SH "SEE ALSO"
\fIRFC 812\fP: NICNAME/WHOIS
.PP
\fIRIPE-223\fP: RIPE NCC Database Documentation
.PP
Detailed help on available flags can be found in \fIRIPE-223\fP or in
the help file which can be obtained with the command:
.IP
.B whois -h whois.ripe.net HELP
.SH HISTORY
This program closely tracks the user interface of the whois client
developed at RIPE by Ambrose Magee and others on the base of the
original BSD client.
I also added support for the protocol extensions developed by David
Kessens of QWest for the 6bone server.
.SH AUTHOR
.B Whois
and this man page were written by Marco d'Itri <\fImd@linux.it\fP>
and are licensed under the GPL.
